### PR TITLE
Photon field bug

### LINKED ISSUE #414: Error in 4D propagation simulation with PhotoPionProduction module
**Describe the bug**
By running a simple CRPropa (version 3.2-37-g5364e8af) 4D simulation of propagating nuclei, an error related to the PhotoPionProduction module arises. Explicitly "error: no photon found in sampleEps, please make sure that photon field provides photons for the interaction by adapting the energy range of the tabulated photon field."   

Is the bug related to the physics in CRPropa? No

**To Reproduce**
One can simply run the example in the CRPropa documentation: https://crpropa.github.io/CRPropa3/pages/example_notebooks/sim4D/sim4D.v4.html . It is about the 4D propagation of protons.

**Expected behavior**
It is expected the simulation of the 10000 protons' propagation. However, the error stops the code very soon. 

**System (please complete the following information):**
 - Operating system: Ubuntu Linux 20.04
 - Laptop or computing cluster? Laptop
 - Python version: 3.8.10
 - Swig version: 4.0.1
 - Cmake version: 3.25.1

**Additional context**
If one rules out the processes related to the PhotoPionProduction modules (e.g. with the CMB and EBL) in the 4D propagation, the aforementioned example works.
If one keeps the PhotoPionProduction modules and rules out the ones related to the Redshift (e.g. FutureRedshift(), ObserverRedshiftWindow(), SourceRedshiftEvolution(), etc.), the simulation succeeds. 
The example works if we consider the propagation of electrons or gamma-rays.
It seems to be a conflict between the new release of the PhotoPionProduction module with the Redshift components.

### PR DESCRIPTION
**Pull request by JulienDoerner**
This PR fixes #414. 

Currently the photon density is set to 0 in tabular photon fields for all redshift $z < 0$. 
With this change the density $n(\epsilon, z=0)$ will be used instead. This is of course only an approximation for small future redshifts. Therefore a KISS warning will be given if $z<-1$ is reached.

I also updated the example notebook for the Sim4D in the folder "doc/pages/example_notebooks/Sim4D". This will for the moment not be shown on the documentation website. I would wait for the upcomming revision of the documentation to build it.

### CODE REVIEW

File: src/PhotonBackground.cpp [hunk 1]
```diff
@@ -25,9 +27,20 @@ TabularPhotonField::TabularPhotonField(std::string fieldName, bool isRedshiftDep
...
-		return interpolate2d(Ephoton, z, this->photonEnergies, this->redshifts, this->photonDensity);
+double TabularPhotonField::getPhotonDensity(double Ephoton, double z) const {	
+	if ((this->isRedshiftDependent)) {
+		// fix behaviour for future redshift. See issue #414
+		// with redshift < 0 the photon density is set to 0 in interpolate2d. 
+		// Therefore it is assumed that the photon density does not change from z = 0. This is only valid for small changes.
+		double zMin = this->redshifts[0];
+		if(z < zMin){
+			if(z < -1) {
+				KISS_LOG_WARNING << "Photon Field " << fieldName << " uses futur redshift with z < -1. The photon density is set to n(Ephoton, z=0). \n";
```
Comment (lukasmerten) [inline src/PhotonBackground.cpp:38]: ... future redshift  or even better FutureRedshift

File: src/PhotonBackground.cpp [hunk 2]
```diff
@@ -25,9 +27,20 @@ TabularPhotonField::TabularPhotonField(std::string fieldName, bool isRedshiftDep
...
 
 
-double TabularPhotonField::getPhotonDensity(double Ephoton, double z) const {
-	if (this->isRedshiftDependent) {
-		return interpolate2d(Ephoton, z, this->photonEnergies, this->redshifts, this->photonDensity);
+double TabularPhotonField::getPhotonDensity(double Ephoton, double z) const {	
+	if ((this->isRedshiftDependent)) {
+		// fix behaviour for future redshift. See issue #414
+		// with redshift < 0 the photon density is set to 0 in interpolate2d. 
+		// Therefore it is assumed that the photon density does not change from z = 0. This is only valid for small changes.
```
Comment (lukasmerten) [inline src/PhotonBackground.cpp:34]: [...] from values at z = 0. [...] for small changes in redshift.

File: doc/pages/example_notebooks/sim4D/sim4D.v4.ipynb [hunk 3]
```diff
@@ -54,7 +66,9 @@
     "sim.add(PropagationCK(Bfield))\n",
     "sim.add(FutureRedshift())\n",
     "sim.add(PhotoPionProduction(CMB()))\n",
-    "sim.add(PhotoPionProduction(IRB_Kneiske04()))\n",
+    "ppp_irb = PhotoPionProduction(IRB_Kneiske04())\n",
+    "ppp_irb.setCorrectionFactor(1)\n",
```
Comment (lukasmerten) [inline doc/pages/example_notebooks/sim4D/sim4D.v4.ipynb:70]: Why do you manually change the correction factor? I guess this is a leftover from testing; in that case please remove it to prevent confusion. Otherwise some comment should be added.

**Review by lukasmerten — COMMENTED** [review]
Looks overall good to me.
Some small changes need to be included.

File: src/PhotonBackground.cpp (hunk 1 above)
Comment (JulienDoerner) [reply src/PhotonBackground.cpp]: Done

File: src/PhotonBackground.cpp (hunk 2 above)
Comment (JulienDoerner) [reply src/PhotonBackground.cpp]: done

File: doc/pages/example_notebooks/sim4D/sim4D.v4.ipynb (hunk 3 above)
Comment (JulienDoerner) [reply doc/pages/example_notebooks/sim4D/sim4D.v4.ipynb]: Yes it is only left over from testing. I changed it back to the previous version.

**Comment by lukasmerten** [comment]
Ok from my side know. However, it would be good if someone who was not involved in the bug fix discussion in Bochum gives the final approval.
