### PR TITLE
Memory management in Variants

### LINKED ISSUE #493: Memory management in BreakingCondition
For context, I ran several simulations inside a loop, varying mass composition to see the energy spectrum at the Earth. I noticed that the RAM consumption was exceedingly high after some time. Further inspection revealed that RAM usage was steadily increasing during my 3D simulations, and the only way to free up that memory was by closing the program. 

After debugging, I think the problem is related to the breaking conditions I used, which are `MinimimEnergy` and `MaximumTrajectoryLength`. I came up with a minimum reproducible example by modifying this [1D example](https://crpropa.github.io/CRPropa3/pages/example_notebooks/sim1D/sim1D.html#Simulation-Setup) on the documentation.

**To Reproduce**
```
from crpropa import *

# simulation setup
sim = ModuleList()
sim.add( SimplePropagation(1*Mpc, 100*Mpc) )
sim.add( Redshift() )
sim.add( MaximumTrajectoryLength( 2000 * Mpc ) ) # Important part

# observer and output
obs = Observer()
obs.add( Observer1D() )
sim.add( obs )

# source
emissionDirection = Vector3d(-1, 0, 0) # Change to (1, 0, 0) to trigger MaximumTrajectoryLength
source = Source()
source.add( SourceUniform1D(1 * Mpc, 1000 * Mpc) )
source.add( SourceDirection( emissionDirection ) )
source.add( SourceRedshift1D() )

# power law spectrum with charge dependent maximum energy Z*100 EeV
# elements: H, He, N, Fe with equal abundances at constant energy per nucleon
composition = SourceComposition(1 * EeV, 10 * EeV, -3)
composition.add(1,  1,  1)  # H
composition.add(4,  2,  1)  # He-4
composition.add(14, 7,  1)  # N-14
composition.add(56, 26, 1)  # Fe-56
source.add( composition )

# run simulation
sim.setShowProgress(True)
sim.run(source, 100_000_000, True)
```

In this example, I noticed two things. First, the `Observer` object correctly manages inactive particles, since running this simulation as it is didn't increase my RAM usage significantly, as shown in the following `htop` command output: 
image

But if I trigger the breaking condition by changing the source emission direction to `Vector3d(1, 0, 0)`, the RAM usage increases and there is no obvious way for me to decrease it:
image

**Expected behavior**
Based on what I showed earlier, I expected the breaking conditions to behave similarly to the observer object. That is, freeing up 
particles once they meet the condition, thus making them inactive. 

**Additional context**
This is a problem for me because, at some point, I am using `ParticleCollector` to rerun simulations from saved files, but after some time the outputs of these extra simulations are like this:
image

Which gave me the hint that this was a memory-related problem.

### PR DESCRIPTION
**Pull request by JulienDoerner**
fixes #493: 

The `abstractConditions` added a property to the candidate on the rejection. Up to now it only adds the key `Rejected`. I added the module name as the default Value for the flag. 

Also the variant (in which this key is stored), does not have the right destructor. If it is deleted, the type of the variant was not passed to the `clear` function. Therefore no deletion of the variant was possible. This leaded to the bug in the memory consumption.

### CODE REVIEW

File: include/crpropa/Module.h [hunk 1]
```diff
@@ -59,7 +59,17 @@ class AbstractCondition: public Module {
 	void setMakeAcceptedInactive(bool makeInactive);
 	void setRejectFlag(std::string key, std::string value);
 	void setAcceptFlag(std::string key, std::string value);
+
+	void printRejectFlag();
```
Comment (lukasmerten) [inline include/crpropa/Module.h:63]: Do we need the print methods or are they just for debugging?

File: include/crpropa/Module.h [hunk 2]
```diff
@@ -59,7 +59,17 @@ class AbstractCondition: public Module {
...
+	void printAcceptFlag();
+};
+
+class DeactivateModule: public AbstractCondition {
```
Comment (lukasmerten) [inline include/crpropa/Module.h:67]: Is it used somewhere or just a general module to deactivate the candidate? 

In this case I would simply call it `Deactivation` as we use nouns for other modules, too, e.g. `MaximumTrajectoryLength`, etc.

Please also add short comment for documentation.

File: include/crpropa/module/Observer.h [hunk 3]
```diff
@@ -281,6 +281,17 @@ class ObserverTimeEvolution: public ObserverFeature {
 	DetectionState checkDetection(Candidate *candidate) const;
 	std::string getDescription() const;
 };
+
```
Comment (lukasmerten) [inline include/crpropa/module/Observer.h:284]: What's the difference compared to the `MaximumTrajectoryLength` module?

File: src/Module.cpp [hunk 4]
```diff
@@ -19,8 +19,7 @@ void Module::setDescription(const std::string &d) {
 
 AbstractCondition::AbstractCondition() :
 		makeRejectedInactive(true), makeAcceptedInactive(false), rejectFlagKey(
-				"Rejected") {
-
+				"Rejected"), rejectFlagValue( typeid(*this).name() ) {
```
Comment (lukasmerten) [inline src/Module.cpp:22]: This would allow to check which module deactivated the candidate, right?

**Review by lukasmerten — CHANGES_REQUESTED** [review]
I have not yet checked if it fixes the actual bug, but in principle it looks good to me. When I have verified the fix and my comments are addressed, I am happy to merge.

File: include/crpropa/Module.h (hunk 1 above)
Comment (JulienDoerner) [reply include/crpropa/Module.h:63]: This is intended for the debugging. Up to now there is no getter function for the key and value of the reject/accept flags. 
One could also think about a real get-function, but this would return a pair of strings, where users can easily be confused by the ordering of the key / value.

File: include/crpropa/Module.h (hunk 2 above)
Comment (JulienDoerner) [reply include/crpropa/Module.h:67]: This is a general module, also intended for debugging. This makes it easier to reproduce the original error as they are faster in deactivating the candidate. 

I will rename it.

File: include/crpropa/module/Observer.h (hunk 3 above)
Comment (JulienDoerner) [reply include/crpropa/module/Observer.h:284]: The first difference is that is Observer based. In this case it is easier to combine different break conditions, having them in the same observer. In principle all functionality could be received with the `MaximumTrajectoryLength`. 

In the practical solution there are two small differences: 
1. The Observer implementation does not have the accept/reject flags, which might reduce the output, if all properties are enabled. 
2. The Observer implementation does not have the overhead with the `observerPositions`. In case without them, the size of the list is checked in every propagation step.

File: src/Module.cpp (hunk 4 above)
Comment (JulienDoerner) [reply src/Module.cpp:22]: Yes, this is the idea. This function was already implemented earlier but the value was not set correctly. I think the module name as default is a good starting option, without going through all modules and set it by hand.

File: include/crpropa/module/Observer.h (hunk 3 above)
Comment (JulienDoerner) [reply include/crpropa/module/Observer.h:284]: I removed this feature as it does not bring a new functionality. Same can be done with `ObserverTimeEvolution` with a single time step.

File: include/crpropa/Module.h (hunk 1 above)
Comment (JulienDoerner) [reply include/crpropa/Module.h]: I have changed it to a get function which returns key & value.

**Comment by JulienDoerner** [comment]
The error also occurred for setting a property to a candidate, but only if the property is of type STRING. 

    for i in range(10_000_000): 
      c = Candidate() 
      c.setProperty("k", "str")

will give the same issue as discussed before. With the explicit delete this issue is solved. 

The only remaining point is related to the `AssocVector`. 

Python gives the warning
` swig/python detected a memory leak of type 'Loki::AssocVector< std::string,crpropa::Variant > *', no destructor found.`
when running the following example: 

     c = Candidate()
     c.properties 
     c.isActive() 
     
One solution could be to change the `AssocVector` to `std::map` which should have the same functionality, or does someone no a difference why we should keep the `AssocVector`?

**Comment by rafaelab** [comment]
Hi @JulienDoerner 
In the last exchange you said there is a problem with `AssocVector`.
Is that fixed? Do you think the PR is good to go with this issue unaddressed?

**Comment by JulienDoerner** [comment]
Hey @rafaelab, 

the `AssocVector` gives a warning `swig/python detected a memory leak of type 'Loki::AssocVector< std::string,crpropa::Variant > *', no destructor found.`
At the moment I have not found any real problem, therefore I would suggest leaving it as it is for the moment. 

The underlying problem from #493 is solved with the fixes here.

**Comment by rafaelab** [comment]
Fine with me. But apparently there are a few comments by @lukasmerten that were not addressed (or at least, they were not marked as resolved, such that I cannot  approve the PR).

**Comment by JulienDoerner** [comment]
Hey @rafaelab, 
There was only one question about the usage left. I marked it as resolved, and you should be able to approve it now.
